### ISSUE TITLE
Starting LaseWeb - config issues

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#10]
Looks like LaserWeb is looking for ethernet connectivity configuration even when connecting by USB. I get the following errors:
Checking : subnet1 : NOT SET
Checking : subnet2 : NOT SET
Checking : subnet3 : NOT SET
Checking : smoothieIp : NOT SET

This causes the ! incomplete config error to pop up.

**Comment by ghost** [comment]
Fixed

**Comment by funinthefalls** [comment]
Thanks
