### ISSUE TITLE
Proportional Feed rate adjustment

### ISSUE THREAD

**Issue by fumblz-n-action** [openhardwarecoza/LaserWeb3#103]
after some conversing with Ariel it has come to our attention that on the fly adjustment of the proportional feeds would make an awesome enhancement. being able to adjust while running could potentially aid in fine tuning each laser system in a minimal amount of time. this enhancement would also help generate less scrap material when working with new material

**Comment by solarmill** [comment]
That's a brilliant idea.

**Comment by ghost** [comment]
note we need to get #106 in place first

**Comment by gndprx** [comment]
I have this on my CNC and it's very useful. I was actually looking for this feature while testing today and noted that it would be a huge benefit.

**Comment by ghost** [comment]
#106.  (: needs to be done before this can start

**Comment by ghost** [comment]
Moved to wishlist on the readme https://github.com/openhardwarecoza/LaserWeb3/commit/b39c56a24a7de76afdbf95dd3e28ae12f6bf6c8c so I can close the issue for now
