### ISSUE TITLE
Serial Enhancement:  Jump-the-queue for realtime feedrate commands, etc

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb3#106]
I implemented https://github.com/openhardwarecoza/LaserWeb3/blob/master/server-smoothie.js#L263 in the backend (unshift puts the new gcode in the front of the queue array)

But its needs enhancement on the Frontend: If we are playing = true, then any commands snet should be sent as this instead so it lands in front of the queue

Right now, if you send say M220 overrides it lands BEHIND the job in the queue

**Comment by ghost** [comment]
PS: needs this in place before we can do #103

**Comment by ghost** [comment]
Moved to wishlist on the readme https://github.com/openhardwarecoza/LaserWeb3/commit/b39c56a24a7de76afdbf95dd3e28ae12f6bf6c8c so I can close the issue for now

**Comment by cprezzi** [comment]
I started implementing overrides to the frontend. The idea is to extend the DRO with displays for feed and speed overrides (% values) with buttons at side, to increase/decrease/reset the overrides.
What do you think about that?

**Comment by ghost** [comment]
Love it!  Go for it!  Sliders for overrides (:

**Comment by cprezzi** [comment]
I think sliders are the wrong choice because of the way how overrides work in GRBL. GRBL has commands for increase or decrease by 1% or 10% and a reset command but no direct set of a % value. So my idea was to have a +, - and reset button aside a input-box which shows the actual % value. The override could be changed by either push one of the buttons or type in the value directly to the input box.

**Comment by ghost** [comment]
Ahh ok didn't know that.  Smoothie is M220 S[percentage]

**Comment by cprezzi** [comment]
Good to know. I will try to implement smoothie version too, even if I don't have a smoothieboard (jet).

**Comment by ghost** [comment]
@arthurwolf (;

**Comment by cprezzi** [comment]
Overrides for GRBL are working now, but I'm not perfectly happy jet. It's not very comfortable to only have +/- 1% buttons, but additional +/- 10% buttons would take to much space (see https://github.com/cprezzi/LaserWeb3/tree/Overrides) :)

![dro overrides](https://cloud.githubusercontent.com/assets/5457949/19866102/1d224626-9f9f-11e6-9056-e7e11f1c3295.jpg)

@openhardwarecoza - Should I add a new "overrides" branch to your repo, or do you first want to test on my branch?

**Comment by cojarbi** [comment]
Claudio

Maybe you could add a colapsable section bellow the  F and S K also you could please this on the same line

## 

Ariel Yahni

On Mon, Oct 31, 2016 at 1:21 PM -0500, "Claudio Prezzi" notifications@github.com wrote:

Overrides for GRBL are working now, but I'm not perfectly happy jet. It's not very comfortable to only have +/- 1% buttons, but additional +/- 10% buttons would take to much space (see https://github.com/cprezzi/LaserWeb3/tree/Overrides) :)

@openhardwarecoza - Should I add a new "overrides" branch to your repo, or do you first want to test on my branch?

**Comment by cprezzi** [comment]
What about pushing shift + button to get large stepps or stay on button for continous changes?

**Comment by cprezzi** [comment]
I have implementet ctrl + button for large stepps and klick and hold for repeat.

**Comment by ghost** [comment]
If this is an seperate branch, feel free to bring it over to Master too.  The best feedback from our average user comes from "force the change on them and see if they rave or complain"

**Comment by ghost** [comment]
I merged it into Master... 

![overrides](https://cloud.githubusercontent.com/assets/7695323/20646894/1142020c-b48e-11e6-829b-9c6f6418d325.PNG)
