### ISSUE TITLE
Feed rate

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#11]
If you set move rate to 30 in the config, when generating raster gcode it sets the rate to 20mm/m I thought we had changed to mm/s?

**Comment by funinthefalls** [comment]
Here is the start of the gcode:
;gcode generated by LaserWeb
; Laser Min: 0%
; Laser Max: 100%
; Black Speed: 10mm/min
; White Speed: 40mm/min
; Resolution (mm per pixel): 0.3527777777777552mm
; Laser Spot Size: 0.2mm
; Laser Feedrate: 30mm/min
; X Offset: 0mm
; Y Offset: 0mm

The feed rates are all mm/m

**Comment by magicsmoke** [comment]
Can confirm. Will give a shot fixing.

**Comment by magicsmoke** [comment]
Got it working. Made a pull request into master with fix.

**Comment by funinthefalls** [comment]
Thanks

**Comment by funinthefalls** [comment]
Works great, thanks for the fix.

**Comment by ghost** [comment]
Gents!  Now you are breaking us!   We multiply what you want in mm/sec on the UI wih ×60 on the gcode si it gets back to mm/min which the firmware needs!   If you don't fix it back to mm/min which is the unit the firmware understands you make our macines 60× slower...

**Comment by magicsmoke** [comment]
Uhhh, that's what I did in commit #7668d5a ... Check line 110 in raster.js, I times the value by 60...

The commit fixed the issue. Correct me if i'm wrong.

**Comment by ghost** [comment]
Alright,  maybe i shouldn't do code review at 4:30am lol.

**Comment by funinthefalls** [comment]
I only merged it because it made sense to me...wasn't 4:30 in the morning for me....lol
