### ISSUE TITLE
Settings check is never satisfied.

### ISSUE THREAD

**Issue by MacTheApple** [openhardwarecoza/LaserWeb3#113]
After filling out all the "required" settings, pressing save, and refreshing leaves me with the " Incomplete Config Please complete configuration" banner at the top of the settings page and the  ": MISSING CONFIG: You need to configure LaserWeb for your setup. . Click Settings  on the left, and work through all the options"
banner in the console. 
The only way to make these banners go away is to fill out all the settings fields, even the ones that are  "optional" , which makes them seem not really that optional at all.

**Comment by krolco** [comment]
Which browser are you using?

**Comment by krolco** [comment]
Just to double check what we are debugging, are you using the latest version of the code? I'll assume you are.

I looked at the code, and the only code path that should cause the banner to appear is if you are missing a required setting. Are there any log lines in the console on the page in red that say "Missing required setting:"? If you can post the log output from startup, that would be helpful also.

**Comment by MacTheApple** [comment]
I'm using the current version of chrome.
The 2 settings that are shown as optional in the interface, but are required in the systemlog are "start gcode" and "end gcode"  I have been solving this by just putting an M5 in each spot.
in systemlog:
Missing required setting: endgcode
Missing required setting: startgcode
in settings:
Start G-Code (Optional)
End G-Code (Optional)

**Comment by openhardwarecoza** [comment]
A recent bug was introduced when localstorage.js was refactored,  ignored
it for now...

**Comment by ghost** [comment]
For those who want to bugfix: https://github.com/openhardwarecoza/LaserWeb3/blob/master/public/js/localstorage.js#L16    (after refactored from what we used to have (from older commit:  https://github.com/openhardwarecoza/LaserWeb3/blob/dd71d92be663b39b5bb567a5fba550e99e8ec903/public/js/localstorage.js#L61  - see how I ignored some params  (;)

@lautr3k 's refactor broke that a little

**Comment by krolco** [comment]
I just submitted #118 for this.

**Comment by krolco** [comment]
@MacTheApple can you please test this now? Thanks!

**Comment by MacTheApple** [comment]
Tested and Fixed, 
Thank you.

**Comment by gfetters** [comment]
This problem is back.  I can not save settings even if I fill out all settings.  I am running on a raspberry pi 3.  latest build

**Comment by ghost** [comment]
Screenshot of the syslog where it does the check?

**Comment by funinthefalls** [comment]
I just did a git pull and loaded LaserWeb. I removed any setting that was optional and refreshed the browser. The software behaved as expected, no configuration errors in the syslog. I am running Windows 10, and latest version of Chrome. LaserWeb version 30420. Tried various combinations of empty optional settings, still not able to reproduce.
