### ISSUE TITLE
process start sequence

### ISSUE THREAD

**Issue by fumblz-n-action** [openhardwarecoza/LaserWeb3#116]
since some recent updates i have not been able to "one click" start a job. in order to start a job i need to click the run button... after it completes the homing sequece i have to click the "connect" button in order for it to continue processing the gcode. depending on the branch of smoothie firmware i'm using i first complete a G28 or $H sequence to home the laser before starting a job

**Comment by ghost** [comment]
Any clues in the nodejs terminal log?

**Comment by krolco** [comment]
Is this still happening?
