### ISSUE TITLE
Inherit raster dpi when tracing

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#126]
At this moment when tracing is executed the result will take a default 25.4dpi. 
Does it make sense to inherit the same dpi from the source or leave it bigger so you can see the result plus adjust accordingly?

**Comment by ghost** [comment]
Would make a lot of sense to inherit

**Comment by krolco** [comment]
I think I have this all fixed up now... required just a bit of digging. Will get it merge through shortly.

**Comment by krolco** [comment]
OK, I merged this up in #131. Give it a swing!

**Comment by cojarbi** [comment]
working great thanks

**Comment by krolco** [comment]
I'm going to close this one. Let me know if you have trouble.
