### ISSUE TITLE
Laser Focal Length / Calibration Offset

### ISSUE THREAD

**Issue by krolco** [openhardwarecoza/LaserWeb3#134]
Value manually entered after calibration process has been run. This can either be a correction to a preset focal length or a corrected focal length value.

**Comment by krolco** [comment]
Total Laser Focal Length, Material Thickness, and Cutting Mat Thickness are all on the UI.

I have it hooked up to raster generation, but not to SVG/DXF generation yet (coming soon). This stuff is hooked up in the emblaser branch.

**Comment by krolco** [comment]
This should be coded now. Please test.

**Comment by ghost** [comment]
@krolco maybe I'm being blonde but I dont see the commit for this?

**Comment by krolco** [comment]
It is (was?) the Z-Focus height param on the Size settings panel -- should be 0 for most cases, but according to @DarklyLabs can contain an offset for calibration for a specific machine. It is in the source code I'm looking at, but I'll make sure tonight that it it didn't get damaged during any recent merges.

**Comment by krolco** [comment]
You can see some work on it here: https://github.com/LaserWeb/LaserWeb3/commit/d9b7528dc9474862f9f7063b2ce32f0f5f5ba2d9

**Comment by ghost** [comment]
Closing - wont be fixing LW3 anymore
