### ISSUE TITLE
Air-Assist Attached Checkbox

### ISSUE THREAD

**Issue by krolco** [openhardwarecoza/LaserWeb3#136]
Air-Assist attached checkbox
With the air-assist nozzle attached, this prevents z-height going too low and colliding with the material.
Without the nozzle attached, laser head can move 50mm.
With nozzle attached, laser head can move 10mm.

Per @DarklyLabs: laser head should be able to move down 8mm above surface, leaving 2mm clearance above the material.

**Comment by krolco** [comment]
Checkbox is on the UI, but not enforced yet. Coming soon. It's in the emblaser branch.

**Comment by ghost** [comment]
https://github.com/LaserWeb/LaserWeb3/pull/193

**Comment by ghost** [comment]
Closing - wont be fixing LW3 anymore
