### ISSUE TITLE
Cutting Mat Installed checkbox

### ISSUE THREAD

**Issue by krolco** [openhardwarecoza/LaserWeb3#137]
Cutting Mat installed checkbox
This adds a value to thickness of material based on the cutting mat thickness.

**Comment by krolco** [comment]
This is implemented as a thickness in MM instead of a checkbox. It's on the UI in the emblaser branch, and partially hooked up (rasters honor this, but other gcode generation doesn't yet).

**Comment by ghost** [comment]
https://github.com/LaserWeb/LaserWeb3/pull/193

**Comment by ghost** [comment]
Closing - wont be fixing LW3 anymore
