### ISSUE TITLE
WebRTC Webcam doesnt work on localhost / https issues with WebRTC

### ISSUE THREAD

**Issue by krolco** [openhardwarecoza/LaserWeb3#139]
Currently camera feature does not work on OSX

**Comment by DarklyLabs** [comment]
Something to note is that there doesn't appear be a way to select which camera to use on systems with multiple cameras.

This is important when working on a laptop with an inbuilt camera and an external USB camera attached.

**Comment by copet80** [comment]
Which feature does not work on OSX? Which browser?

Chrome:
I tried on 192.168.0.10:8000, it complains about getUserMedia() not allowed on unsecured origins, so changing it to localhost:8000 works.

Safari:
Doesn't support getUserMedia() at all, even one of the well-known webcam libraries like https://github.com/jhuckaby/webcamjs requires Flash Player for Safari support.

My opinion on this would be to either insist users to use Chrome for webcam feature, or create an installer with Cromium running underneath it, i.e. using Electron. Any thoughts?

**Comment by ghost** [comment]
WebRTC needs https to work. The nodejs localhost is served as http.

**Comment by ghost** [comment]
It does print the error in the console log,  if you enable Video overlay,
then refresh the browser. .

**Comment by ghost** [comment]
Affects all OSs after recent Chrome updates

**Comment by ghost** [comment]
@copet80 any update on solutions you came up with?

**Comment by lautr3k** [comment]
Fixed on optimization branch

**Comment by ghost** [comment]
Resolved in the Optimisation branch by @lautr3k
