### ISSUE TITLE
Optimize cut path on multiple passes on open vector

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#144]
When cutting an open vector in multiple passes, for example a line in 2 passes, it does 2 left to right passes instead of running one left-right and then one right-left

**Comment by krolco** [comment]
Peter and I were chatting about adding a path optimizer to LW3 -- I think it might catch this kind of bad behavior. Hopefully something we can get to!

**Comment by funinthefalls** [comment]
https://hackaday.io/project/4955-g-code-optimization  Maybe this can be used?

**Comment by jorgerobles** [comment]
Better! http://parano.github.io/GeneticAlgorithm-TSP/

**Comment by ghost** [comment]
@cojarbi I dont know of any optimisers that would reverse lines to optimise it. And for CNC that would be totally wrong too (converting a climb cut to a conventional cut in the name of optimising speed...)
The bigger secret here is properly closed vectors (polyline dxf for the win)

That said, still happy to accept a pull for adding something to make less G0 moves (:

**Comment by ghost** [comment]
Moved to wishlist on the readme https://github.com/openhardwarecoza/LaserWeb3/commit/b39c56a24a7de76afdbf95dd3e28ae12f6bf6c8c so I can close the issue for now
