### ISSUE TITLE
WIP Feedrate for job buttons

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb3#15]
I added the UI elements, but they need to be functionalised in ./js/jog.js 

The two fields are `jogfeedxy` and `jogfeedz`   (I gave Z its own for leadscrew Z machines that need a slow feed)

**Comment by magicsmoke** [comment]
Jogging isn't working anymore.

**Comment by ghost** [comment]
(; help find the bugs and fix them? I am on the road this week.
