### ISSUE TITLE
Generate G-Code from Toolpaths

### ISSUE THREAD

**Issue by DaveCalaway** [openhardwarecoza/LaserWeb3#150]
Hi guys,
i have a problem when i used the "tree" function, i made a gif for help us: https://goo.gl/TtBoMv
In short, when i hit Generate G-Code on Toolpaths window, nothing happens.

**Comment by ghost** [comment]
See open issue 52: Tree CAM is an upcoming feature. Not fully implemented
yet

**Comment by ghost** [comment]
Duplicate #52
