### ISSUE TITLE
Changed format for live feedback in Grbl 1.1c

### ISSUE THREAD

**Issue by beikeland** [openhardwarecoza/LaserWeb3#156]
Terminal output from the new live feedback in Grbl 1.1c:

```
WARN: Connecting to Port /dev/ttyUSB0,115200
Connected to /dev/ttyUSB0at 115200
Recv:
Recv: Grbl 1.1c ['$' for help]
Recv: [MSG:'$H'|'$X' to unlock]
Recv: <Alarm|MP<Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|Ov:100,100,100>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|WCO:0.000,0.000,0.000>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|Ov:100,100,100>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|WCO:0.000,0.000,0.000>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|Ov:100,100,100>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|WCO:0.000,0.000,0.000>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.|Ov:100,100,100>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
Recv: <Alarm|MPos:0.000,0.000,0.000|Bf:16,128|F:0.>
WARN: Closing Port /dev/ttyUSB0
```

Can update with motion etc when I can be by the machine and test later if it helps.

**Comment by beikeland** [comment]
The error messages are reduced to error codes, overview of codes to look up is here i believe https://github.com/gnea/grbl/blob/edge/grbl/report.h

**Comment by beikeland** [comment]
Its been pointed out that you can  use ´#define USE_CLASSIC_REALTIME_REPORT´ to retain the old feedback for now.

https://github.com/gnea/grbl/blob/edge/grbl/config.h#L288

**Comment by ghost** [comment]
@beikeland I updated the regex to split on "|" too, have another test and let me know (:

**Comment by iceman1979** [comment]
Are you specifying $10=3 or something else?

**Comment by cprezzi** [comment]
This 'quick and dirty' method of parsing | in one go with : and , is not reliable, because the amount and order of parameters in statusReport from GRBL depends on configuration and status. On my machine, I only got MPos from GRBL when $10=3. With $10=2 I got WPos, but no MPos, so x/y/z is not at the right position.
It's better to parse it correctly by first break it in segments of piped-parts, then separate by : & , to get param: val, val, val (number of values depending on param). 

@peter: It seems you only patched | in "public/js/grbl.js", but this is not used for display update. You need to patch it also in "public/js/socketcomms.js" which seems to updates the X/Y/Z Position display and BullseyePosition.

**Comment by cprezzi** [comment]
If you like, I can send you my code when I'm back in the office tomorrow.

**Comment by cprezzi** [comment]
Here is my code for socketcomm.js (tested with GRBL v1.1d, should also work with v0.9):

```
function updateStatus(data) {
    // till GRBL v0.9: <Idle,MPos:0.000,0.000,0.000,WPos:0.000,0.000,0.000>
    // since GRBL v1.1: <Idle|WPos:0.000,0.000,0.000|Bf:15,128|FS:0,0|Pn:S|WCO:0.000,0.000,0.000>

    // Extract state
    var state = data.substring(data.indexOf('<') + 1, data.search(/(,|\|)/));

    // Extract WPos (set $10=2!)
    var start = data.search(/wpos:/i) + 5;
    if (start){
        var pos = data.substr(start).split(/,|\|/, 3);
    }

    if (state == 'Alarm') {
        $("#machineStatus").removeClass('badge-ok')
        $("#machineStatus").addClass('badge-notify')
        $("#machineStatus").removeClass('badge-warn')
        $("#machineStatus").removeClass('badge-busy')
    } else if (state == 'Home') {
        $("#machineStatus").removeClass('badge-ok')
        $("#machineStatus").removeClass('badge-notify')
        $("#machineStatus").removeClass('badge-warn')
        $("#machineStatus").addClass('badge-busy')
    } else if (state == 'Hold') {
        $("#machineStatus").removeClass('badge-ok')
        $("#machineStatus").removeClass('badge-notify')
        $("#machineStatus").addClass('badge-warn')
        $("#machineStatus").removeClass('badge-busy')
    } else if (state == 'Idle') {
        $("#machineStatus").addClass('badge-ok')
        $("#machineStatus").removeClass('badge-notify')
        $("#machineStatus").removeClass('badge-warn')
        $("#machineStatus").removeClass('badge-busy')
    } else if (state == 'Run') {
        $("#machineStatus").removeClass('badge-ok')
        $("#machineStatus").removeClass('badge-notify')
        $("#machineStatus").removeClass('badge-warn')
        $("#machineStatus").addClass('badge-busy')
    }
    $('#machineStatus').html(state);

    if (Array.isArray(pos)){
        $('#mX').html(pos[0]);
        $('#mY').html(pos[1]);
        $('#mZ').html(pos[2]);
        if (bullseye) {
            setBullseyePosition(pos[0], pos[1], pos[2]); // Also updates #mX #mY #mZ
        }
    }
}
```

**Comment by cprezzi** [comment]
Tested with GRBL v1.1, should also work with GRBL v0.9 ;)

**Comment by cprezzi** [comment]
Don't forget to set the new params:
$10 = 2 (for WPos & Buffer State)
$30 = max. Laser PWM
$31 = min. Laser PWM
$32 = 1 (Laser mode on)

**Comment by ghost** [comment]
I would love a pull request to fix it better (:

**Comment by beikeland** [comment]
For $32=1 to be fully useful does not the generated G code need to have S
parameter added to all moves, and remove the M03/M05 commands to turn
off/on laser between segments? Use S0 to turn off laser instead.

I can help test, but thats the limit of my scope for now.

**Comment by ghost** [comment]
LW3 does not automatically add m3/m5 unless you add that to laseron/Laseroff commands in settings,  gcode. The default (Smoothieware uses this too)  is blank commands for on/off.  Then g0 moves = laser off,  g1 =laser on.  We have S values on every line.

**Comment by iceman1979** [comment]
I set M3 S0 in my start code block and M5 in my end code block. I also set the laser off command to S0

The S value on a line is only required if it changes but it doesn't hurt to have it in there for every line.

**Comment by cprezzi** [comment]
For me it worked with or without setting M3/M5. If M3/M5 is not configured in settings, you need to set M3S0 in the Start-Code and M5 in End-Code. 
In LaserMode, GRBL accepts S Values in each G-Move and sets the correct PWM for the Laser.

@openhardwarecoza: I'd like to send a pull request, but I'm not used to work with git, so give me some time to find out ;)

**Comment by openhardwarecoza** [comment]
Ok all merged now (: Closing this one

**Comment by ghost** [comment]
@cprezzi  - after this fix, we seem to have a trailing > that doesnt get removed? 

![trailing slash](https://cloud.githubusercontent.com/assets/7695323/19756281/bf1482d2-9c1b-11e6-9920-8347618a5cde.JPG)

**Comment by krolco** [comment]
I stepped through the parsing code from the PR, and it looks like it returns correct results -- no trailing greater-than in the parse. I couldn't figure out where this comes from either.

**Comment by cprezzi** [comment]
This could probably happen when WPos-Values are not followed by another param (like with GRBL v0.9). 
Need to delete the > in the string before parsing WPos.

**Comment by cprezzi** [comment]
@openhardwarecoza - I updated master. Could you please check if it's corrected now?

**Comment by cprezzi** [comment]
Good documentation of GRBL v1.1 protocoll changes: https://github.com/gnea/grbl/blob/edge/doc/markdown/change_summary.md

**Comment by ghost** [comment]
Remember that Smoothie feedback is parsed by the same function...

<Idle,MPos:49.5756,279.7644,-15.0000,WPos:0.0000,0.0000,0.0000>

This is the output from Smoothie...

**Comment by iceman1979** [comment]
The output will be different based on your $10 setting in GRBL. I have mine
set to $10=2 based on the comments in the code but ideally it should be set
to $10=1 so that GRBL is not sending back the buffer bytes remaining. This
is meant for debugging only and is recommended to not use this for
production runs as it can cause latency issues with GRBL.

You can't ask too much of these little arduinos lol

**Comment by iceman1979** [comment]
Maybe we can look at the welcome message and set a flag that indicates smoothi or GRBL?

**Comment by ghost** [comment]
The two are so close that theres almost no point.  We did do hectic auto
detection on LaserWeb (v1)  and it later became a nightmare.  Thats why in
later versions we made it configurable through a gcode settings and macro
panel so it really works with anything

**Comment by iceman1979** [comment]
Cool!

**Comment by cprezzi** [comment]
@iceman1979 - Please check the new settings for $10 of GRBL v1.1 (https://github.com/gnea/grbl/blob/edge/doc/markdown/settings.md). With $10=1 you only get MPos instead of WPos, which breaks DRO. You have to set $10=0 if you don't want Buffer info.

**Comment by cprezzi** [comment]
@openhardwarecoza - Thanks for the mention. I checked it and Smoothie parses exatly like old GRBL, so my last fix should also be good for smoothie ;)

**Comment by cprezzi** [comment]
It would be possible to use MPos for DRO, if WPos is not available. Should I implement that?

**Comment by iceman1979** [comment]
I believe the options for $10 would be 0, 1, 2, 3 depending on if you want MPos, WPos, with or without buffer data. Is LW3 not capable of supporting all of those options? Meaning can we only use work position with LW3?

If it doesn't break LW3 then I would suggest supporting all of the $10 options.

**Comment by ghost** [comment]
@cprezzi , yes if wpos is not available fall back to mpos. That would be elegant

Another option, we can always send $10 on connecting to force a state we want:

https://github.com/openhardwarecoza/LaserWeb3/blob/master/server-grbl.js#L186-L191

(Mind you i think we need something other than 'version' for Grbl on line 191 there anyway)

Anyway, adding a line there to send $10=whateveritmustbe is an option.

**Comment by maudette01432** [comment]
@ Peter - I was thinking that same thing.  My concern with that is it would be changing a configuration (EEPROM) setting and there is the possibility that you won't be able to exit gracefully and set it back. Maybe only warn and leave it up to the user before writing new configuration...and/or document recommended GRBL configuration.

**Comment by cprezzi** [comment]
@iceman1979 - Not exactly. Mode 3 is not supported anymore (read the link I posted). GRBL v1.1 only supports $10 = 0, 1 or 2. $10=1 means MPos insted of WPos, which is not parsed in LW jet.

**Comment by cprezzi** [comment]
@openhardwarecoza - If we set $10 by code (which I do in the start G-Code at the moment), then we don't need a fallback for MPos.
How about Smoothie? Do we allways get WPos from it, or do we have to set the right params too?

**Comment by ghost** [comment]
Smoothie only returns one kind of grbl status line in response to '?' as
far as I know...  But lets check with @wolfmanjm if i am correct

**Comment by cprezzi** [comment]
I think it's easyer to add the MPos fallback. This way, it doesn't matter, what's set in $10.

**Comment by ghost** [comment]
Agreed.  If its not too much trouble,  that would be best

**Comment by cprezzi** [comment]
It's just 3 lines of code ;)

**Comment by iceman1979** [comment]
@cprezzi I did, that's where I got it from :)

> Use the table below enables and disable reporting options. **Simply add the values listed of what you'd like to enable**, then save it by sending Grbl your setting value. For example, the default report with machine position and no buffer data reports setting is $10=1. If work position and buffer data are desired, the setting will be $10=2.

@chamnit, please correct me if I'm miss stating this.

It is a bit mask system
$10=0 (0000, WPos without buffer data)
$10=1 (0001, MPos without buffer data)
$10=2 (0010, WPos with buffer data)
$10=3 (0011, MPos with buffer data)

**Comment by wolfmanjm** [comment]
@openhardwarecoza Smoothie only returns a fixed data for the ? command the realtime MPOS and WPOS. I don't see any reason to make it more complicated.

**Comment by ghost** [comment]
@wolfmanjm thanks (: -  yes please dont make it more complex. See here we
are fixing parsers again for grbl lol.  Yours,  still works lol.

**Comment by chamnit** [comment]
@iceman1979 : Yes. You are correct.

@openhardwarecoza : For the record, the recent change in v1.1 was necessary to cram significantly more real-time data (overrides, pin states, accessory states, buffer states, line numbers, realtime feed and speeds, etc), still reduce the overhead involved with serial comm, and make it easier for GUIs to maintain their code down the road. It was a necessary evil, which I know is painful but trust me that it's for the better.

Having both MPos and WPos in the same message is a complete waste, because all you need is the coordinate offset, which rarely changes. Once you have it, it's a simple arithmetic to compute the other position vector.

**Comment by ghost** [comment]
#firmwarewars lol

**Comment by iceman1979** [comment]
@chamnit Thanks, I appreciate the confirmation. I want to make sure I'm not saying something incorrect.

**Comment by iceman1979** [comment]
@openhardwarecoza lol, too funny. Don't hate but you know I have to put my vote in for GRBL :)

**Comment by cprezzi** [comment]
@iceman1979 - Sorry for the mistake. You was right and I was wrong (hmmm) :(

@chamnit - I realy like the new features from v1.1 a lot and the new format for status reports makes parsing a child's play ;)

**Comment by cprezzi** [comment]
PS: I'm allready playing with the overrides ;)

**Comment by iceman1979** [comment]
Lol, no worries. I'm just glad I was right for once lol. That doesn't happen too often for me :)

**Comment by cprezzi** [comment]
Did anybody test if this version is still working with smoothie?

**Comment by cprezzi** [comment]
This feature was merged to master branch, so I close the issue now.

**Comment by cspwcspw** [comment]
Two small questions about parsing the feedback:

**Comment by cspwcspw** [comment]
Suppose grbl is reporting WPos and occasionally also sends WCO status.  (Easier if we assume no axis movement is occurring.)  If the active workspace changes (e.g. I send a G10 to select a different workspace), will the new WCO be reported immediately on my next status poll, so that the WPos and "most recently received WCO" are always in sync? Or is it possible to get a "new" WPos value based on my new workspace selection, even though I haven't yet seen the new WCO? 

I have a related issue when my GUI attaches to an already initialized and running machine.  Until I've received the first WCO, I cannot properly calculate MPos. 

And then just for my own interest: what is the reason for providing a choice between reporting WPos or MPos? Would it not be cleaner to say "We always report MPos.  Deal with it!"  As chamnit has pointed out, it is a simple matter for a GUI to convert from either to the other once WCO is known.  

Thanks

**Comment by cprezzi** [comment]
@cspwcspw: Your post is related to Grbl, not LaserWeb! Please post your question on https://github.com/gnea/grbl/issues.
