### ISSUE TITLE
Add a gcode tool path simulator

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#157]
Is it possible to get a 3D gcode simulator where the tools moves over the path ?

Maybe one of these https://github.com/search?o=desc&q=gcode+simulator&s=forks&type=Repositories&utf8=%E2%9C%93

**Comment by ghost** [comment]
We ripped all that out a couple months ago to reduce the memory footprint of the 3D viewer.  Adding that code back in, is going to be soooo much work
