### ISSUE TITLE
[Question] Why do the settings need to be reloaded after saving?

### ISSUE THREAD

**Issue by jorgerobles** [openhardwarecoza/LaserWeb3#160]
Taking a brief look to the code cannot find the reason the interface alerts to reload page for settings to take effect. localStorage should be updated immediatly. Is there any application feature that prevents this?

**Comment by ghost** [comment]
The threejs grid size,  for example,  needs a refresh

**Comment by ghost** [comment]
Which @tbfleming is addressing already with React
https://plus.google.com/101442607030198502072/posts/VzfbPqr26Ye in LW4

**Comment by ghost** [comment]
(Closing this one since thats basically resolved in LW4)
