### ISSUE TITLE
[Proposal] MVC like pattern for LaserWeb

### ISSUE THREAD

**Issue by jorgerobles** [openhardwarecoza/LaserWeb3#162]
Following #161, I want to raise a proposal for LS3~LS4 decoupling code, namely separating UI functions from core application, further splitting on libraries, etc., so the code could be improved better from different contributors and aspects.
Maybe it could be ported to Angular/Ember frameworks in a future

**Comment by ghost** [comment]
I totally agree,  have a look at the lw4 codebase: switching to ReactJS

**Comment by jorgerobles** [comment]
Ow Yeah!

**Comment by openhardwarecoza** [comment]
Which @tbfleming is addressing already with React
https://plus.google.com/101442607030198502072/posts/VzfbPqr26Ye

**Comment by ghost** [comment]
PS: I gave you push access to LW4 a while ago, but I see the invitation is still unaccepted

https://github.com/openhardwarecoza/LaserWeb4/invitations

**Comment by jorgerobles** [comment]
Found! I missed that. Thanks!

**Comment by ghost** [comment]
All cool! Anyone else who wants push access, just ask (:  - this project is way bigger than me (:
