### ISSUE TITLE
Multiple Images are not all on z0 

### ISSUE THREAD

**Issue by gndprx** [openhardwarecoza/LaserWeb3#166]
When opening a combination of images for multiple operations, not all layers appear to be set at z0. A gap between the layers seems to cause a forced perspective issue when attempting to align both images.

G+ Discussion thread
https://plus.google.com/u/0/105504973000570609199/posts/3fJfdp7ocFP

Video examples
https://www.youtube.com/watch?v=PGZzGrlPbPo
https://www.youtube.com/watch?v=TUpH-MH_iAU

Original files:
[FPD 2016 Insert.zip](https://github.com/openhardwarecoza/LaserWeb3/files/544992/FPD.2016.Insert.zip)

**Comment by gndprx** [comment]
This is on version 30379

**Comment by ghost** [comment]
Rasters are now loaded 0.01mm below the Z0 point. If I put them exactly on Z0, then the obscure the vectors... So I have to drop it a little in Z to allow the renderer to render the Vectors visibly in front. 
It was at -0.9 though which was way too much
