### ISSUE TITLE
Life feed and spindle/laser overrides

### ISSUE THREAD

**Issue by cprezzi** [openhardwarecoza/LaserWeb3#174]
I got feed and spindle/laser overrides working for Grbl (>1.1d) and Smoothie via USB.
The GUI elements are only shown when a compatible board is connected via USB.

Somebody like to test?

**Comment by cojarbi** [comment]
I have a grbl cnc on 1.0, I can update to 1.1

## 

Ariel Yahni

On Wed, Nov 2, 2016 at 11:29 AM -0500, "Claudio Prezzi" notifications@github.com wrote:

I got feed and spindle/laser overrides working for Grbl (>1.1d) and Smoothie via USB.

The GUI elements are only shown when a compatible board is connected via USB.

Somebody like to test?

**Comment by cprezzi** [comment]
You are welcome to test this version is on branch "overrides".

**Comment by cprezzi** [comment]
Overrides branch got an update. 

![dro overrides](https://cloud.githubusercontent.com/assets/5457949/20229399/77d5a22e-a856-11e6-9279-f3d9acad0057.gif)

Long press on +/- override buttons now continously count values up/down and CTRL+button makes larger steps (10% instead of 1%).
Override fields are only shown if a compatible board is connected through USB (GRBL>v1.1 or Smoothieboard).

**Comment by beikeland** [comment]
Seems to be working well; but I can't help to think that the % override is less interesting than the absolute value.

I would at least find it more useful to see that I'm running at F: 120 than knowing the G-code is for F100 and I'm at 120%.

So the question becomes how to display the absolute feeds and speeds and maintain the override control without cluttering the interface, maybe something like so which also adds individual zeroing for axis?
![image](https://cloud.githubusercontent.com/assets/2701678/20305079/f6da2a92-ab33-11e6-8d3e-27f96a2f179d.png)

**Comment by ghost** [comment]
@beikeland since F and S actual valus changes constantly during the job (especially in rasters) the override percentage makes more sense.

**Comment by ghost** [comment]
merged to master... closing this issue

![overrides](https://cloud.githubusercontent.com/assets/7695323/20646921/cc5a4162-b48e-11e6-8f08-8ef2227fa508.PNG)
