### ISSUE TITLE
Smoothie M999 reset after error/end stop hit

### ISSUE THREAD

**Issue by Pooky1306** [openhardwarecoza/LaserWeb3#176]
It seems that after smoothie goes to halt mode, LW3 can't send commands anymore.
However the M999 command is required to clear the halt state but it just goes in the buffer. It would be cool to be able to send the M999 command  from LW.

Btw hard reset is working but in some case a restart of node.js is required.

**Comment by ghost** [comment]
Agreed! Will do asap

**Comment by ghost** [comment]
Implemented today

Please test!

![alarm state](https://cloud.githubusercontent.com/assets/7695323/20649394/c2328440-b4c7-11e6-9e5f-ac7e3ba6c043.PNG)

**Comment by cprezzi** [comment]
Seems to work perfect :)
Hint: you should also dump the grblBufferSize array when you dump gcodeQueue, otherwise the character counting would get messed up. I have corrected that with my last commit.
