### ISSUE TITLE
"Laser test" button for jog-tab

### ISSUE THREAD

**Issue by cprezzi** [openhardwarecoza/LaserWeb3#180]
It would be usefull to have a "weak laser" button to manually fire the laser with low power. This is often used on diode laser engravers for positioning. The power of such a test shot should be configurable in the settings (weak laser power).

**Comment by funinthefalls** [comment]
Wolfmanjm added this to the cnc-firmware bin, however I have an issue with the way he implemented it. You can pulse a low power test fire, but it stays on until you issue an off command for it, which I find to be very awkward to do, especially when trying to align mirrors. A work around is to make a macro that fires on a short Z axis move, but that causes conflicts with those that have adjustable Z axis platforms, or a Z axis slide. I would love to see your idea for a weak test fire button of a very short duration be added.

**Comment by cojarbi** [comment]
Anthony remember he did that based on his diode Laser setup. 

## 

Ariel Yahni

On Mon, Nov 14, 2016 at 7:42 AM -0500, "Anthony Bolgar" notifications@github.com wrote:

Wolfmanjm added this to the cnc-firmware bin, however I have an issue with the way he implemented it. You can pulse a low power test fire, but it stays on until you issue an off command for it, which I find to be very awkward to do, especially when trying to align mirrors. A work around is to make a macro that fires on a short Z axis move, but that causes conflicts with those that have adjustable Z axis platforms, or a Z axis slide. I would love to see your idea for a weak test fire button of a very short duration be added.

**Comment by iceman1979** [comment]
Can this be changed to a click on / click off behavior?

**Comment by funinthefalls** [comment]
When aligning mirrors on a CO2 laser, the pulse duration should only be about 1/10th of a second. Impossible to click n and off that fast.

**Comment by ghost** [comment]
Easy enough to do with js: fire 10; dwell 0.1; fire 0" or whatever the
syntax.  Does Smoothie have 'dwell?'  @wolfmanjm

**Comment by wolfmanjm** [comment]
dwell would be G4 P100  (milliseconds) or G4 S2 (seconds).

also it would be better to be fire 10 then  G4 P100  then fire 0ff

**Comment by iceman1979** [comment]
Well, that explains why that pulse feature exists in another software program I use :) The author of that program also has a CO2 laser :) I don't know what syntax he uses to do this but I have tested it on my O'scope.

Sounds like something we might be able to do in software though.

**Comment by cprezzi** [comment]
When we adjust the mirrors on the Lasersaur we just cut a short line with low power, as we don't have a test button there.
I like the solution that the host software can activate and deactivate the laser (without move). This way, duration and power can be configured in the software, depending on the needs.

**Comment by cprezzi** [comment]
I see two different usages:
- On CO2 lasers, it would be useful to have a test shot button, which fires for preconfigured time and power.
- On diode lasers, it would be better to have a toggle button which switches the laser on or off at preconfigured power.

We could add two settings values like "test fire power" and "test fire duration" and make duration 0 to be permanent on/off to hande both cases.

But this feature depends on the firmware implementations.

**Comment by cprezzi** [comment]
I have coded this feature in branch "overrides". Please test :)

**Comment by cprezzi** [comment]
You must set "Laser Test Power" and "Laser Test Duration" in G-Code Settiings first.

- A duration of zero means the <Laser Test> button acts as a toggle on/off button. 
- If duration is set to more than 0, one button click fires the laser for this duration in ms.

**Comment by cprezzi** [comment]
@chamnit: Does Grbl also support G4 for delay (like Smoothie)? At the moment I have coded it with a setInterval on the host side, but would prefer to let grbl handle the timing.

**Comment by cprezzi** [comment]
Ok, found it. G4 Px on Grbl uses seconds (not milliseconds, like Smoothie). Changed it.

**Comment by ghost** [comment]
Merged to Master. Closing Issue
