### ISSUE TITLE
LaserWeb causes causes computer crash upon wake

### ISSUE THREAD

**Issue by wolfpaw98** [openhardwarecoza/LaserWeb3#181]
OS X Yosemite seems to consistently crash upon wake.
Setup:
- Smoothie board plugged into the computer via USB,
- K40 off or powered on,
- LaserWeb3 (latest build) running in Chrome,
- Mac goes to sleep.
When woken, OS X crashes.

Has anyone else experienced this issue?

**Comment by ghost** [comment]
Wont be LW.  We dont interact with the OS. . Nodejs does,  maybe open an
issue on nodejs or node-serialport
