### ISSUE TITLE
Carving/Engraving does not generate any G1 codes

### ISSUE THREAD

**Issue by mdkroyer** [openhardwarecoza/LaserWeb3#186]
The alpha value for each pixel in laserraser.js is always 0 and lumaGray is always 1.

**Comment by mdkroyer** [comment]
Forget it... I am an idiot. Had canvas blocked in my browser.

**Comment by ghost** [comment]
I suspect you forgot to complete the Configuration (things like max pwm s
value,  laser spot size and the like...) -  on startup the log will tell
you if your configuration is ok or some required values missing

**Comment by mdkroyer** [comment]
It is working now. I had a browser extension running that blocks canvas fingerprinting of my browser. Unfortunately it also blocked LaserWeb3 canvas operations. I removed the extension and all problems were gone.
