### ISSUE TITLE
Streaming Protocol for GRBL

### ISSUE THREAD

**Issue by cprezzi** [openhardwarecoza/LaserWeb3#188]
I have implemented the grbl streaming protocol in branch overrides. Could somebody please test.

Should I make the protocol swichable between ping-pong and streaming, or is it ok to move to the streaming protocol completely?

**Comment by ghost** [comment]
@chamnit would probably say Go Streaming! (:
This is awesome!

**Comment by ghost** [comment]
I've pulled over overrides into Master so we can get a couple more users testing

I accidentally grabbed some TinyG work (nice coincidence, my new controller from Synthetos should arrive this week... the new G2 based laser specific controller of theirs...)

I cleaned up a error in server-smoothie.js too

**Comment by cprezzi** [comment]
Good you checked server-smoothie as I was not able to test because the lack of a smoothie board.

**Comment by cprezzi** [comment]
I started working on TinyG but didn't came to far. I try to use the comm library from TinyG but will need a board to finish work.
