### ISSUE TITLE
! incomplete config error

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#19]
!incomplete config error. I have made sure that I did configure all the required settings. Here is a copy and paste of the console:
Checking whether you have configured LaserWeb :

Checking : rapidSpeed : NOT SET undefined
Checking : autoClose : Yes
Checking : subnet1 : OPTIONAL
Checking : subnet2 : OPTIONAL
Checking : subnet3 : OPTIONAL
Checking : smoothieIp : OPTIONAL
Checking : laserXMax : 330
Checking : laserYMax : 230
Checking : spotSize : 0.2
Checking : startgcode : G28
Checking : laseron : OPTIONAL
Checking : laseroff : OPTIONAL
Checking : lasermultiply : 255
Checking : homingseq : G28
Checking : endgcode : G28
Checking : useOffset : Disable
Checking : imagePosition : TopLeft
Checking : useNumPad : Disable
Checking : useVideo : Disable
MISSING CONFIG: You need to configure LaserWeb for your setup.

It is the rapidfeeds setting that does not seem to save, even after entering a value in the field.

**Comment by funinthefalls** [comment]
This is the contents of my settings backup json file:
{"autoClose":"Yes","debug":"undefined","endgcode":"G28","homingseq":"G28","imagePosition":"TopLeft","laserXMax":"330","laserYMax":"230","lasermultiply":"255","laseroff":"","laseron":"","lastUsedBaud":"250000","lastUsedPort":"COM3","loglevel":"ERROR","rapidSpeed":"undefined","rapidspeed":"40","smoothieIp":"","spotSize":"0.1","startgcode":"G28","subnet1":"","subnet2":"","subnet3":"","tour_current_step":"0","tour_end":"yes","useNumPad":"Disable","useOffset":"Disable","useVideo":"Disable"}

There appears to be two entries for rapidspeed, first one says "undefined", second one says "40"

**Comment by ghost** [comment]
Fixed
