### ISSUE TITLE
New branch for Go Lang

### ISSUE THREAD

**Issue by cprezzi** [openhardwarecoza/LaserWeb3#192]
@openhardwarecoza : Please Peter, start a new branch for your Go lang work, as long as it is not finished. Master should be the productive, stable version.

**Comment by ghost** [comment]
With the conversation in https://plus.google.com/u/0/+PetervanderWalt/posts/Ynh5ERrKKpb?sfc=true and the find by Ben Delarre (https://github.com/felixrieseberg/windows-build-tools) I am going to continue trying to get the Emblaser branch working on Windows. So probably wont need to have a golang branch

**Comment by cprezzi** [comment]
So, is it ok that I rollback your changes for golang, as they broke master branch for grbl?

**Comment by ghost** [comment]
Yip go for it
