### ISSUE TITLE
Emblaser-electron issues: Grbl support

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb3#195]
I think this one is better handled with @cprezzi 's plan to have a single server.js for all firmwares. But opening issue so we dont forget

**Comment by cprezzi** [comment]
The single server.js is finished. Please test on Smoothie. Testing on Grbl is looking good.

@openhardwarecoza : Probably you want to merge that to your Electron-LW3 branch?

**Comment by ghost** [comment]
Merged into Electron-LW3 already https://github.com/LaserWeb/LaserWeb3/commits/Electron-LW3
Busy compiling new installer...

**Comment by ghost** [comment]
Tested on Smoothie, and no issues

**Comment by ghost** [comment]
New installer ready to test with Grbl... Works with Smoothie https://drive.google.com/file/d/0B-UxBll2MapjX1NWMDVzWWhUbms/view?usp=sharing
