### ISSUE TITLE
No preview on any tab on the last commit 

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#199]
This shows bellow 
TypeError: Cannot set property 'visible' of undefined (http://localhost:8000/js/viewer.js on line 63)

**Comment by LaserGreg** [comment]
Not sure what that means Ariel
I have seen that error before though

**Comment by ghost** [comment]
Yip i know i broke it.  I was busy removing treecam,  and accidentally pasted from code when i added the tinyg code.   In bed already will fix in the morning...
It involves removing references to FillTreeCam()  in tabs.js and main.js
