### ISSUE TITLE
Abort job button & next move

### ISSUE THREAD

**Issue by Pooky1306** [openhardwarecoza/LaserWeb3#200]
Tried safety features and new reset functions this evening and ran in a strange thing:

- while running job, pressed abort job button
> machine stops, alarm state triggered popup shows
- press option 1: reset and clear queue
> all ok
- Next I sent a jog move Z 10mm up, as if I was removing the broken tool or whatever from the part
> Go to Z+10 BUT I got X and Y move, like if the last line or last move was still in some sort of buffer

**Comment by LaserGreg** [comment]
Yes - I've seen that too, not sure if it is a USB Buffer or what - but it
definitely occurs - for me it was the Home command hanging around when the
carriage didn't home due to communication problems with the board.

**Comment by ghost** [comment]
What did the Queue number indicator on the right above the dro show?  If the queue was in LaserWeb's queue it will have a number there.  Of the queue was already sent to the controller,  its a different story (i'll need to investigate)

**Comment by cprezzi** [comment]
@Pooky1306 : Do you use Smoothie or Grbl? Which version?

**Comment by ghost** [comment]
I know he's on a smoothie (:

**Comment by ghost** [comment]
https://plus.google.com/collection/UAoPsB is his setup with one of my
designed (Brian Bland built)  Smoothiebrainz

**Comment by Pooky1306** [comment]
Yup ;)
Found some clues:

Just tested again with a gcode files containing only X moves, then only Y then combined XY back and forth.
The gcode must be more than the buffer size otherwise it works ok.

When abort occur, the DRO values displayed change to the last point but the machine stays in place.
After reset the queue is cleared but when a move is sent, the machine goes back this last point because at this moment there's a difference between the physical position and the one displayed in DRO.

If not clear, example:
Gcode:
G0 X0 Y0
G0 X50 Y50
G0 X0 Y0
G0 X50 Y50
etc.. many times

Aborted during a X50 Y50 to X0 Y0 move
machine stops at about X25 Y25
reset and clear > DRO now displays X50 Y50 (last pos in gcode) but the machine is still stopped at X25 Y25
Did a jog Z+10
machine goes from X25 Y25 Z0 to X50 Y50 Z10 . DRO and machine are sync.

**Comment by cprezzi** [comment]
Hm. This behaviour should not be possible as Smoothie executes all commands in the planner before stopping (after a hold command). 

What exactly do you mean with "pressed abort job button"?
Did you click the "Stop" Button on LaserWeb or a hardware button connected to you smoothieboard? Or something else?

**Comment by Pooky1306** [comment]
Yes all tests are done by pressing the Abort job button in LW.

I can do a video if it helps. I can reproduce the problem on each try

**Comment by Pooky1306** [comment]
Note that the change of DRO values occurs when the abort button is pressed, not after reset.

**Comment by LaserGreg** [comment]
Just curious - what OS and machine are you using?  Mine is an old Laptop
running Win 8.1 - now being upgraded to Win 10.  I came across several
articles detailing how the Vista/7/8 windows Serial to USB drivers
sometimes do not flush the buffers correctly - Not a LaserWeb problem - but
a windows problem. Going to Win 10 is supposed to fix it.  We'll see if it
does.

**Comment by Pooky1306** [comment]
Hmm I'm on a Pipo X9 win10

**Comment by LaserGreg** [comment]
Ok Thanks !  I have experienced something similar to your observations,
contact me off list if you like and I'll go over it with you.  It may shed
some light or it may be just me - but all knowledge is good knowledge as
they say.

73
Greg
VE7GPG

**Comment by openhardwarecoza** [comment]
Greg,  please don't join these conversations on Github.  This is for the devs and technical people.  You are not a level that adds any value.  Please

**Comment by cprezzi** [comment]
Ok, I was able to replicate this issue.

On "abort job" we send a reset command to smoothie to stop the machine immediately, which smoothie does. Then you get the alarm popup because smoothie sends an alert. After clearing the alert, we get the following warning (from smoothie) in the SysLog area: "WARNING: After HALT you should HOME as position is currently unknown". That's all expected.

But the reaction when jogging z after all this is not expected, and I cannot explain it. It looks to me like an issue of smoothie for the moment, but we have to investigate some more.

@openhardwarecoza : We should probably extract an example for this issue and ask Arthur and Jim. What do you think?

**Comment by ghost** [comment]
@arthurwolf @wolfmanjm

**Comment by cheton** [comment]
This is similar to a question that I asked two days ago (https://github.com/cheton/cnc/issues/94#issuecomment-264863350).

@wolfmanjm mentioned that it's necessary to home ($H) after unlocking ($X) from alarm mode. After homing, it should be able to work as expected.

**Comment by cprezzi** [comment]
I did expect that the machine has to be homed after a hold (like the waring sais), but it's still weird that the machine moves in x/y when it's jogged in z (if not homed).

This could be a security issue when somebody stopped his CNC because of a broken milling cutter and then needs to jog to safe z height before homing.

**Comment by wolfmanjm** [comment]
I do not think this is a smoothie issue. sending control X will clear the smoothie job queue and usually even leaves the position for where the actuators currently are.(it may need homing as an abrupt stop on some machines will cause it to lose steps or coast).
If it moves in X or Y after this then I suspect there is a gcode in the comms queue on the host side which was not cleared. It is possible that if a gcode is sent after the control X that will be stuck in the USB buffer, but any gcode received by smoothie after control X will be rejected with a `error:Alarm lock` instead of an OK, the host MUST handle this as an immediate stop and clear its buffers and queues. I suspect LW does not currently handle it correctly? BTW I use control X all the time from a console and have never seen this issue. (Not to say it may be some odd edge case with LW and smoothie communication).
(EDITED: in grbl mode it does not send !! it sends alarm lock, but if not in grbl mode it will send !!, it may be necessary for LW to handle both, unless LW requires smoothie to be in grbl mode)

**Comment by Pooky1306** [comment]
The strange thing during the test is the sudden change on the DRO (which are read from smoothie if I'm right ?)

Test method to produce the issue:
> Gcode:
G0 X0 Y0
G0 X50 Y50
G0 X0 Y0
G0 X50 Y50 etc.. many times
Abort during a X50 Y50 to X0 Y0 move
machine stops at about X25 Y25 > DRO values immediately change to X50 Y50 (last pos in gcode) but the machine is still stopped at X25 Y25 (unsync?)
reset and clear 
Do a jog Z+10
machine goes from X25 Y25 Z0 to X50 Y50 Z10 . DRO and machine are sync.

**Comment by wolfmanjm** [comment]
how is it aborting?
How is it reading the DRO?
How is it resetting and clearing?

M114 for instance reads the last milestone which is the last received gcode which is different from the real time position.
? reads the current actuator position and uses FK to get the cartesian position.
It looks like it is reading the last milestone instead of the actual position.

**Comment by wolfmanjm** [comment]
Also what version of smoothie are you running?

**Comment by wolfmanjm** [comment]
It definitely looks to me like LW is sending another gcode AFTER it sends the abort.

**Comment by wolfmanjm** [comment]
try this.. put your test gcode on sdcard.
connect with a console.
play /sd/testfile.g
wait for the X50 X50 and send control X
do a ? and see where it is
do $X to clear the alarm
do ? to see where it is (should be same as above)
then do your Z move

if this works correctly then it is not a smoothie issue but a LW communication glitch.
(FWIW this works for me with the current edge)

**Comment by cprezzi** [comment]
@wolfmanjm : Thank you for stepping in.

Here is what we do on a abort:
port.write('!');                     // send hold
gcodeQueue.length = 0;   // clear our the queye
port.write("M5\n");            // make sure laser is off (-> eventually this is the problem?)
port.write(String.fromCharCode(0x18));  // send ctrl-x

The following alarm triggers a popup that the user must clear (sends M999).

In parallel, there is an intervall that sends ? every 250ms.
The position response reads WCO for the DRO.

I can check the exact smoothie version tomorrow in the office, but it is firmware-cnc w/o grbl mode.

**Comment by wolfmanjm** [comment]
don't send the hold.... that is what is causing the issue on smoothie, just send control X.

**Comment by wolfmanjm** [comment]
also do not send M5 that is not required and you cannot send anything anway after ! or control X
Control X is abort and it turns everything off.

**Comment by wolfmanjm** [comment]
and you should use $X to clear the alarm

**Comment by cprezzi** [comment]
Ok thanks. That all is old behaviour which I am reworking now. I will try your tipps tomorrow.

**Comment by cprezzi** [comment]
What is grbl mode for?

**Comment by wolfmanjm** [comment]
As smoothie serves 3d printers which use a nonconforming form of gcode, there is a grbl mode to make responses and gcode more NIST gcode compliant, so it tries to respond with the same responses as grbl does. You need to be using a smoothie firmware that is a cnc build and will be in grbl mode by default (for recent versions).

**Comment by cprezzi** [comment]
Ah ok, then I probably have grbl mode on by default.

**Comment by cprezzi** [comment]
I have reduced the abort behaviour to just send ctrl-x and later on, when the user clears the alarm, we send $X.
@Pooky1306 could you please test again?

**Comment by Pooky1306** [comment]
@cprezzi just tested, same method, same results.
 edit: just did a git pull, nothing else needed ?

**Comment by wolfmanjm** [comment]
There could be an issue if the user pauses (which issues !) then sends control X. try just doing the abort (control X) only without the pause. See if that is different. If it is I may be able to flush something in the USB driver after a pause.

**Comment by cheton** [comment]
Hi @wolfmanjm,

Below are my steps to abort a G-code program against a hold. Do you see any problems here?

1. Clear out the queue
2. Send `~` to resume a hold state
3. Send ctrl-x to abort
4. Unlock Alarm ($X)
5. Retract Z to a clearance height
6. Home ($H)

**Comment by wolfmanjm** [comment]
@cheton skip step 2 it is not needed and may cause issues.
As will aborting while paused possibly.

**Comment by cprezzi** [comment]
@Pooky1306 Yes, git pull should be enough. I will change the behaviour again a bit and get back to test.

**Comment by ghost** [comment]
@Pooky1306 have you tested after the git pull?

**Comment by Pooky1306** [comment]
I'll do it this evening and post results.

**Comment by cojarbi** [comment]
I have tested this as follows:

press abort
press option one > machine stops immediately
selected option 1
Press a macro i have to send my machine to X0 Y0

Result was as expected.

**Comment by Pooky1306** [comment]
Mmh still the same on my machine but there's an error somewhere in my config.  I don't know if it is critical as I use it as that since half a month and just noticed it today by looking on the console.

: Build version: edge-dcf0252, Build date: Nov 27 2016 14:18:23, MCU: LPC1769, System Clock: 120MHz
:  CNC Build
: error:Invalid statement

**Edit: looks like issue201**

@cojarbi when you hit abort, DRO displayed in LW stops at the actual position ? (you need a gcode with long linear moves and longer than buffer size to see that)
**Edit: mine https://drive.google.com/open?id=0B3rOLUu_uwqNdUNuMjZ3aGlHbDg**
What if instead sending X0 Y0 you jog at Z+10 ?

Other point: by mistake I clicked outside the reset pop-up box and it disappeared with the machine still in halt state. Refresh the page bring it back.

**Comment by cojarbi** [comment]
It does stop inmediatly for me but did not try on a longer movement. 

Will try later tonight

⁣Ariel Yahni​

**Comment by cojarbi** [comment]
Ok so i tested you gcode and indeed the behavior is strange.

Gcode does stops inmediatly even if the queved count is not empty ( if empty it also stops ) but:

If the movement is forward the live preview will show the status stop as the origin on the line and my macro G0 X0 Y0 will not work. Pressing other movement buttons will send the head back to the "origin" in a fast movement

If the movement is backwards ( returning from the corner ) the live preview will show the status stop at the end, my macro will work but very slowly

from there i my G0 X0 Y0 macro is not executed but if i press any movement

**Comment by cprezzi** [comment]
@cojarbi : Be aware that this issue is only on smoothie, not Grbl!
