### ISSUE TITLE
Support for imperial units

### ISSUE THREAD

**Issue by donkjr** [openhardwarecoza/LaserWeb3#204]
Currently LW ignores a G20.
**Impact on user:** it renders a Gcode file with imperial units like it was metric. Any Gcode program using G20 will be incompatible with LW
**Solution recommendation:**
As a minimum: I think it should at least post an error to notify the user that it did not render correctly
Ideally I would like to see LW support the G20 code.

For some reason this link needs to be copied and pasted in browser to work.
[https://plus.google.com/113684285877323403487/posts/XLDWJr9Nv8e](url)

**Comment by ghost** [comment]
Internal CAM is all metric.  If user loads external GCODE,  onus is on them to make sure its valid for LW's use (S values in correct places,  correct units,  correct start/emd gcodes,  etc
