### ISSUE TITLE
create windows executables out of node.js application

### ISSUE THREAD

**Issue by mkeyno** [openhardwarecoza/LaserWeb3#209]
sorry to open the ticket for my question but I find couple of tools that can convert node.js file to the executable   file which can be run on different platform , however couple of them not support dynamic source , I was wondering is somebody has tried to perform such task so normal user can use this server without need to install node.js and other  dependencies

**Comment by ghost** [comment]
See the electron branch of this project.  Its coming along,  one open bug upstream on electron-builder though
