### ISSUE TITLE
Set 0 while connected to grbl does not work

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#211]
Pressing Set 0 should set all axis to 0 but while connected to grbl 1.1e its not working for me.

**Comment by cojarbi** [comment]
I have updated the topic since it does zero the axis but it does not update to reflect it

**Comment by cojarbi** [comment]
This also causes another issue ass the preview will not follow the machine movements

**Comment by cprezzi** [comment]
I think you have set your Grbl $10 to 1 not 0. Therefore Grbl is reporting machine coordinates instead of work coordinates. The set zero function can only reset work coordinates.

**Comment by cojarbi** [comment]
OK i just checked and i had it at 3, dont know why.

Thanks its fixed now
