### ISSUE TITLE
High CPU load by web browser

### ISSUE THREAD

**Issue by jekhor** [openhardwarecoza/LaserWeb3#212]
At LW3 opening, Firefox (and chrome) starts to consume CPU too much and don't stop this until tab will be closed or other tab is activated.

At my system, Debian unstable, Firefox 50.1.0, i7-5600U, Firefox loads CPU for 60%.

**Comment by ghost** [comment]
We only support Chrome

Try Laserweb.github.io/LaserWeb4 which has a more lightweight webgl implementation.  Lw3 uses three.js which tends yo need good hardware and good webgl performance (Linux gfx drivers and webgl has always lagged a bit too)

**Comment by ghost** [comment]
Besides,  as we move into LW4 all the more,  its unlikely we'll massively improve LW3.  It works for most people

**Comment by jekhor** [comment]
The same on LW4 in Chrome 55, btw
