### ISSUE TITLE
No GUI feedback when pressing S/F override buttons in GRBL

### ISSUE THREAD

**Issue by mertyGit** [openhardwarecoza/LaserWeb3#217]
Hi,

I minor one, but I see GRBL 1.1 supports S/F override buttons, but I don't see an update in GUI, representing the right number.
Shouldn't there be something in server.js like calculating new spindleOverride and 
`"io.sockets.emit('spindleOverride', spindleOverride)"` under 'grbl' case too ?
(same goes for feedOverride)

Or am I missing something ?

Regards,

Remco

**Comment by cprezzi** [comment]
No, that's not needed as grbl Reports the actual override values with the status Report. If it doesn't work on your system, then there is another Problem. Check your $10 Settings for example.

**Comment by cprezzi** [comment]
Please verify such Problems first on our G+ community with other users before opening an issue here. Issues are only for verified Bugs.
