### ISSUE TITLE
Wiki for ESP8266 needs updating

### ISSUE THREAD

**Issue by hchahine** [openhardwarecoza/LaserWeb3#220]
Couldn't figure out how to fork and edit a wiki myself (and then issue a pull) but there are a couple of broken links in the instructions here:

https://github.com/LaserWeb/LaserWeb3/wiki/Connecting-ESP8266---LaserWeb3---Smoothieware

All references to:
https://github.com/openhardwarecoza/LaserWeb3/blob/master/ESP8266%20Wifi%20Bridge/*

are broken and should now point to:
https://github.com/LaserWeb/LaserWeb3-ESP8266

Hopefully that'll help someone else.

**Comment by cprezzi** [comment]
Thank you. I have corrected the broken links.
