### ISSUE TITLE
CANT UPDATE

### ISSUE THREAD

**Issue by gendebeat** [openhardwarecoza/LaserWeb3#221]
Hello , my syslog says: 
Version currently Installed : 30478
: Version available online on Github : 30539
: NB: UPDATE AVAILABLE! - Execute 'git pull' from your laserweb terminal

i make git pull. but always say the same. 
i cant update. 
i make a new installation and cant use the last versions. 
thanks

**Comment by ghost** [comment]
Press shift f5 to refresh your browser after updating...
