### ISSUE TITLE
GRBL not detected on startup

### ISSUE THREAD

**Issue by Protoneer** [openhardwarecoza/LaserWeb3#222]
I am using LaserWeb3 on a Raspberry Pi directly connected to an ATMEGA328.

On startup LaserWeb3 does not pickup that its GRBL because the RPI serial port does not restart the 328 like on a USB Arduino when connecting.

Is there a way that I can sent a Ctrl-X to the 328 to restart GRBL for LW3 to pick it up?

**Comment by Protoneer** [comment]
Or is there a way that I can tell LW3 that it will always be GRBL connecting?

**Comment by cprezzi** [comment]
Just click the "abort job" button to send a ctrl-x (when connected).

**Comment by cprezzi** [comment]
I could probably do an auto ctrl-x after connect, but I need to test if that causes any issue with other firmwares.
