### ISSUE TITLE
Serial Port

### ISSUE THREAD

**Issue by btcrowe** [openhardwarecoza/LaserWeb3#226]
I have installed Laserweb3 and it opens, but i can not connect to the laser. It won't let me select com port 4 which is the one my laser is on. It doesn't list any ports in the select port pull down.

**Comment by ghost** [comment]
Git is for Bugs. Not for support.  Head over to the google plus community 

If you failed to read the first line of the Readme (telling where to go to get support)  you probably also didnt read the install instructions.  Or you failed to read the syslog (bottom of the LaserWeb web window during startup (errors about no webgl?  Then that pc doesn't support LW... If you have errors during start nothing else will work)

I can point you to reading lessons if that might help

**Comment by openhardwarecoza** [comment]
Scroll to the top of the syslog window in lw

**Comment by openhardwarecoza** [comment]
Scroll to the top of the syslog window in lw's web interface
