### ISSUE TITLE
Serial Port

### ISSUE THREAD

**Issue by btcrowe** [openhardwarecoza/LaserWeb3#227]
I have installed Laserweb3 and it opens, but i can not connect to the laser. It won't let me select comm port 4 which is the one my laser is on. It doesn't list any ports in the select port pull down.

**Comment by ghost** [comment]
You are a special kind of idiot right?  https://github.com/LaserWeb/LaserWeb3/issues/226 i already replied to you,  and you go ahead and open another issue for the same thing.
