### ISSUE TITLE
multilayer cut configuration 

### ISSUE THREAD

**Issue by mkeyno** [openhardwarecoza/LaserWeb3#239]
sorry to open ticket for my question, I've been working with laserweb3 for couple of days but it seems it hasn't proper feature to defined multilayer configuration for cutting purpose such as  inkscape laser plugin , will this feature added in 3 version or 4 version ?

**Comment by tbfleming** [comment]
It's in 4.

**Comment by tbfleming** [comment]
Use https://plus.google.com/communities/115879488566665599508 for questions; we prefer to keep issues for bug reports and feature requests.
