### ISSUE TITLE
Issue with zig-zag rasterisation of bitmap

### ISSUE THREAD

**Issue by andreword** [openhardwarecoza/LaserWeb3#240]
Though this may be down to my configuration, I have found that when rasterising a PNG file on both Laserweb 3 and 4 (1000 dpi image). The 'reverse' path is offset from the normal direction, resulting in a ghosting effect.(see image, and ignore the scratches, it's a piece of scrap copper board)

![pcb1](https://user-images.githubusercontent.com/2720129/30515393-93257b1a-9b1e-11e7-8e7c-3a554fad3676.jpg)

I modified the public/js/laserraster.js to remove the line
    this.dir = -this.dir; // Reverse direction for next row - makes us move in a more efficient zig zag down the image

Though less efficient, this results in the program drawing all raster lines from the same side, and thus removing this ghosting effect, resulting a solid image

If this is down to the file geometry or some other setting I haven't found let me know

An option to disable the zig-zag pattern would be useful

I haven't managed to test this on laser web 4 as yet

**Comment by cprezzi** [comment]
This is not a software issue, it's your hardware that has backlash. You should try to improve the hardware.
I do a lot of raster engraving and never had such "ghosting".

**Comment by andreword** [comment]
Well I'm afraid it is a software issue if the same hardware is used to render with other programs and does not suffer the same issue when rendering in the zig-zag pattern.
Neither does this problem appear on vector movements where gaps would appear in lines

Could you tell me what settings you are using, in particular the dpi of the images you import

**Comment by tbfleming** [comment]
@andreword this is a support issue, not a bug. Ask at https://plus.google.com/communities/115879488566665599508

Most likely cause: your firmware's acceleration or max rate settings are too high. When this happens some things work and some things don't.

**Comment by andreword** [comment]
The image in my post above was taken after running the engraver at slow speed to increase burn time on the painted surface. The engraver also runs at speeds >8 times the speed used for this particular engraving without any issues (except for bitmaps).

When I disable the zig-zag pattern, and only burn in a single direction, the result is as per the attachment
![pcb2b](https://user-images.githubusercontent.com/2720129/30523105-2edd2fb2-9bd3-11e7-8816-d88d0ef529f2.jpg)

If the issue was missing steps or high speeds the effect would also be visible in this image, but it isn't

**Comment by tbfleming** [comment]
Look at the generated gcode. If it's a SW issue then the issue will show up there. If you can't read gcode, then run it through an emulator.
