### ISSUE TITLE
Display path size

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#33]
Show the path size. Want to make sure im scaling to the correct size

**Comment by ghost** [comment]
Elaborate?  Already displaying that on the Quotes tab

**Comment by cojarbi** [comment]
I was referring to the path or raster box / perimeter size. Yes we should have the scale allready but showing the info is useful specially if I scale in LW

**Comment by ghost** [comment]
You mean like this?  

![sizes](https://cloud.githubusercontent.com/assets/7695323/16712241/8bfcd1dc-4681-11e6-8dec-663c1c3aeb7b.PNG)

(Works for any object, raster or vector):  When you click that objects's tab:  We can display more parameters around the dashed line bounding box?

**Comment by cojarbi** [comment]
Thanks,  looks like the perfect place. 

AY
