### ISSUE TITLE
Box preview before real operation

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#34]
As in LW1.

**Comment by ghost** [comment]
A lot more difficult now that we have per layers...

Will need to run Bbox over all objects and calculate max/min points

**Comment by ghost** [comment]
Done!

![bbox](https://cloud.githubusercontent.com/assets/7695323/17012521/96a14790-4f18-11e6-8da3-ab1b6f01eaab.PNG)

**Comment by cojarbi** [comment]
Thanks

AY
