### ISSUE TITLE
Can not generate gcode from bitmap

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#35]
Can not generate gcode from a bitmap I loaded in LaserWeb3. This is the bitmap I have used for testing for quite some time now, so I figure it is not a file issue. It loads the bitmap OK, but generate Gcode does nothing.

**Comment by cojarbi** [comment]
Do you have CNC cam enabled? That would not let you generate code. Maybe post the file

**Comment by funinthefalls** [comment]
That did it, I disabled CNC cam and it worked like a charm. Thanks.
