### ISSUE TITLE
First G1 code has no G1 and F parameter

### ISSUE THREAD

**Issue by ahorn42** [openhardwarecoza/LaserWeb3#37]
The first 3 lines of my generated GCode looks like this:

```
G0 F3000 X15.750 Y0.345
 X15.750 Y0.345 Z0
G1 F1200 X15.750 Y0.345 Z0 S1.00
```

In the second line it's missing `G1 F1200` at the beginning. Note also the line 2 starts with a space character.

**Comment by funinthefalls** [comment]
Can you please attach the file you were working with?

**Comment by ahorn42** [comment]
Till now it happened with all file, but here is one to test [ahorn.svg](https://owncloud.philippberger.de/index.php/s/JaTQSXUyun6SV6s) and the generated gcode when scaled at 500dpi [ahorn.gcode](https://owncloud.philippberger.de/index.php/s/vISE0c3wqes8zX5)

**Comment by ghost** [comment]
Settings -  gcode -  travel speed.  I suspect you left it blank?

**Comment by ahorn42** [comment]
Uhm no, it's set to 50 mm/sec - and it does not look like an placeholder text. Furthermore I discovered that every first G1 after a G0 misses its G1 and F parameter.

**Comment by ghost** [comment]
Heading home now after a 72hour workweek.  Will check tomorrow

**Comment by ghost** [comment]
Checked, and code updated. Please 'git pull' test and let me know if its resolved (:

**Comment by ahorn42** [comment]
Yep, now it works :)

Thanks a lot for this fast fix!

**Comment by ghost** [comment]
Keep the testing and cool ideas coming  (; i'll keep fixing and adding
