### ISSUE TITLE
Z height probe

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#38]
Any chance of getting a Z height probe as a feature?

**Comment by ghost** [comment]
Sigh.  Lol!  Yeah maybe.  But not soon (;

**Comment by cojarbi** [comment]
Can't this be done exactly as 3d printers? Measure / 5ouch the surface and the offset the focal point.? 

Execute this command via macro on LW? 

AY

**Comment by ghost** [comment]
Good point.  We have the awesome smoothieware,  not shit like grbl or
marlin that burdens the host.   #do-investigate -  i recall smoothieware
had a grid probe.  Let the firmware do the heavy lifting

**Comment by ghost** [comment]
Closing the "issue" for now - but we'll definately revisit it later in the CNC cam portion
