### ISSUE TITLE
Weird first line of Gcode

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#39]
There is a weird line of Gcode right after the Y offset line, it is:
"G1 FNan"

I have pasted the first part of the generated code.

; Raster:
; Laser Min: 0%
; Laser Max: 100%
; Black Speed: 3000mm/s
; White Speed: 1200mm/s
; Resolution (mm per pixel): 0.1693333333333225mm
; Laser Spot Size: 0.1mm
; Laser Feedrate: {6}mm/s
; X Offset: 0mm
; Y Offset: 0mm 

G1 FNaN
G0 Y230.000
G0 Y229.831

**Comment by cojarbi** [comment]
I believe that is from the setting  default speed being empty? 

AY

**Comment by ghost** [comment]
Fixed the NaN in https://github.com/openhardwarecoza/LaserWeb3/commit/3895e4786fc57ba61306cf63b731f3ceed193a3c
