### ISSUE TITLE
Please update README.md#supported-firmwares

### ISSUE THREAD

**Issue by trillerpfeife** [openhardwarecoza/LaserWeb3#43]
Thanks for your great work!
Yesterday i was a little bit confused because GRBL doesnt seem to be supported but than i saw the GRBL commit! Yeah. Pleas update https://github.com/openhardwarecoza/LaserWeb3#supported-firmwares so that other people can find it right away.

**Comment by ghost** [comment]
I just want the community to do some testing before i declare it
'supported',  can we give it a day or two?  The commit log usually reads
like a book though

**Comment by trillerpfeife** [comment]
ok thx

**Comment by ghost** [comment]
Updated.  Have three users reporting success.

**Comment by trillerpfeife** [comment]
Mine is also working fine! But pause and abort the job is nor working reliable.

**Comment by ghost** [comment]
Pause and abort,  stops sending commands.  But whatever already left the
wire,  ie ended up on the serial buffer of the controller. Should still
take a few moves to flush.  Does that Match your observation?
