### ISSUE TITLE
Tabbing off y-offset value in bitmap panel resets offsets to 0

### ISSUE THREAD

**Issue by krolco** [openhardwarecoza/LaserWeb3#45]
I tried this on Safari 9.1.1 and Chrome Version 51.0.2704.103 (64-bit), using version 30170 of LW3.

In the CAM:Convert to G-CODE Panel, when I am editing the settings for a bitmap to be engraved, tabbing off the "Y" box in the "Position Offset" section into the "Bitmap Resolution" box causes both the X and Y values in Position Offset to reset to 0.

**Comment by ghost** [comment]
I think its because we monitor keyup on the resolution,  and resolution change is supposed to put it back to 0,0 (so we can redraw the mesh with the new resolution).    If you click out,  instead of Tab,  it works correct right?   In that case I would think the best fix is then to swop their positions,  resolution at the top,  offset below it.  Makes more workflow sense too. Set the size,  then place it

**Comment by krolco** [comment]
Hi, yes, it works if I click. If you move the resolution to the top, it would also be consistent with the "Trace to Vector" output panel (which has the resolution as the first element also)

**Comment by krolco** [comment]
I moved the DPI selection to be the first option on the panel and put the offset right after (since it's likely to be the first things you set) and I moved the trace option to the final option on the panel (since it creates a new tab afterwards). I also moved the offset position to the first option on the DXF panel for consistency; it looks like it was already in that position on the CNC panel. That seemed to fix the problem as you figured above. As soon as I can figure out how to make a pull request, I'll send it in.

**Comment by ghost** [comment]
Agreed (:  -  will do that today then (:

**Comment by krolco** [comment]
I opened pull request #49 for this.

**Comment by ghost** [comment]
Ahh sorry, I didnt see the PR

**Comment by krolco** [comment]
The pull request is for the offset-reset issue. I didn't investigate the Safari issue yet, but if you don't intend to support Safari, that's OK -- I am fine using Chrome, and I'm not particularly good at investigating browser differences. :) If you don't plan on supporting this, you can just close the issue.
Thank you!
Monte

Date: Mon, 25 Jul 2016 21:40:33 -0700

**Comment by ghost** [comment]
Good improvement on the parseFloats - thanks, I manually picked them out of the PR.  PR wont merge, conflicts with work I had commited already - but no problem, this was a small enough commit to just manually copy in the changes.   

Bitmap resolution is now at the top.  

I see you also moved the Trace button - i think it belongs near the top, to avoid confusion (trace first, switch to traced object to adjust its parameters) - if its below scale/etc users may think it "ignores" the settings they just put in above it

I anyway want to rework the trace UI, Potrace.js has a few user definable settings which would be nice to expose.   See https://github.com/kilobtye/potrace/blob/master/potrace.js#L14-L25

I'm thinking a switch widget on the bitmaps's object:  "raster <-> trace" and then if switched to trace, hide the raster options, show the trace options, and the reverse as well

**Comment by krolco** [comment]
Thanks, I saw how you merged it manually. I updated my fork and closed the pull request. No problem on the Trace button -- I liked it better at the bottom, but I hadn't considered the interaction with the parameters :) I think this is all resolved now, so I'll close this. Thanks again!
