### ISSUE TITLE
Bitmap Preview and Trace Preview not working on Safari 9.1.1

### ISSUE THREAD

**Issue by krolco** [openhardwarecoza/LaserWeb3#48]
I don't know if this is known, but the bitmap preview and trace views don't work on Safari 9.1.1 on OS X 10.11.5. I tested with several different bitmaps; they work on Chrome. I've attached one of the affected bitmaps. 
![khador small](https://cloud.githubusercontent.com/assets/459130/17125387/dbda8f5a-52a7-11e6-9af1-58faf0eb2eca.jpg)

**Comment by ghost** [comment]
I dont have access to OSX,  does safari have a Javascript Dev Console?
"(Same as Chrome's Ctrl+Shift+I console)?  If yes can you see if there pops
up any errors?  As a sidenote,  since January we've always said we only
support Chrome.  Since so much of the code relies on the Javascript
engine,  and Chrome's js engine and webgl support is always ahead of the
curve

**Comment by krolco** [comment]
I'll check for an JS errors, but if you intend Chrome only, you can just close this.

**Comment by ghost** [comment]
For now, if you dont mind, lets.  With the whole nodejs thing being easy to cross platform, and chrome being great across all platforms, if we can it'd be great

**Comment by ghost** [comment]
You can run a quick check against http://kilobtye.github.io/potrace/  to see if its potrace's code,   or LaserWeb - that conks out (:

**Comment by krolco** [comment]
Something goes wrong loading the bitmap -- I see "Sanity Check" output from raster.js:69 that shows the wrong size for the bitmap (0,0), even though the Safari debugger shows the right size for it. Everything else after that goes bonkers because it computes a zero-area bounding box. I might try to look a bit deeper.

**Comment by ghost** [comment]
Aha,  so its not on the trace code,  but rather up near the file open.
Check the readFile function in main.js

**Comment by krolco** [comment]
Fyi, I just submitted PR #58 for this.

**Comment by ghost** [comment]
Merged (:
