### ISSUE TITLE
Home button not working

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#6]
ReferenceError: homeMachine is not defined (http://localhost:8000/# on line 256)

**Comment by ghost** [comment]
Ethernet or USB?

**Comment by cojarbi** [comment]
usb

On Thu, Jun 9, 2016 at 11:43 PM, Peter van der Walt <
notifications@github.com> wrote:

> Ethernet or USB?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/openhardwarecoza/LaserWeb3/issues/6#issuecomment-225091903,
> or mute the thread
> https://github.com/notifications/unsubscribe/APrsFqhvrXPXRuV8T0FIc1s4r2fNQiubks5qKOtygaJpZM4Iyh9h
> .

## 

Ariel Yahni
