### ISSUE TITLE
Delayed coordinates display update when manual jogging.

### ISSUE THREAD

**Issue by Tegeon** [openhardwarecoza/LaserWeb3#61]
I found the coordinates showing X/Y/Z position are delayed (looks like machine 'Run' status is frozen for a little while) when manually jogging from 0,0,0 to X- or Y- or Z+ (jog by just one click using 10mm jogging distance or few quick subsequent clicks to multiply that distance). After few moments the displayed value gets to the right one and status goes to 'Idle'.

I am running default config.txt and no motors connected at the moment, latest firmware and latest git pull.

**Initial 0,0,0 position:**
![zrzut ekranu 2016-07-29 18 55 33](https://cloud.githubusercontent.com/assets/12793131/17257015/70b45b72-55c0-11e6-84a3-bd1bc7028357.png)

**One click to Y-:**
![zrzut ekranu 2016-07-29 18 55 50](https://cloud.githubusercontent.com/assets/12793131/17257017/73538312-55c0-11e6-8e58-33ef43e48ddc.png)

**Three clicks to Z+:**
![zrzut ekranu 2016-07-29 19 13 39](https://cloud.githubusercontent.com/assets/12793131/17257049/91d361cc-55c0-11e6-9b32-5f113236972d.png)

**Same as previous some seconds later (Z coord updated to 30):**
![zrzut ekranu 2016-07-29 19 16 03](https://cloud.githubusercontent.com/assets/12793131/17257132/ee258d2e-55c0-11e6-80cc-83e110f27a15.png)

**Comment by ghost** [comment]
Usb or ethernet?

**Comment by Tegeon** [comment]
USB at the moment. I need to solder WiFi or wait for Ethernet module delivery.

**Comment by ghost** [comment]
Ok,  will check in the morning.  Exact build of firmware you are on?

**Comment by Tegeon** [comment]
Version currently Installed : 30188
Version available online on Github : 30188
Your version of LaserWeb is Up To Date!

**Comment by ghost** [comment]
(: I meant smoothie version,  so i test from same build.  Run 'version'  on
the command console. May need to catch output on the nodens if it doesnt
pop into browser log

**Comment by Tegeon** [comment]
Here it is:
Smoothie
ok
version
Build version: master-27197b7, Build date: Jul  4 2016 04:10:42, MCU: LPC1769, System Clock: 120MHz

**Comment by ghost** [comment]
I havent been able to fix this just yet... I'm going to close the issue for now though, it boils down to a larger underlying thing on the serial buffer...
