### ISSUE TITLE
SVG Load fails: Property "Length" of null

### ISSUE THREAD

**Issue by emteeoh** [openhardwarecoza/LaserWeb3#64]
I have several files I created today in Inkscape that don't work in LW3. These aren't merely "unclosed": they fail to load. The error in the console is: TypeError: Cannot read property 'length' of null (http://127.0.1.1:8000/lib/threejs/three.min.js on line 11)

One problem: I can't distribute these files publicly... Is there a way to privately attach a file?

**Comment by ghost** [comment]
Object to path,    and   settings,  tool,  autoclose.

**Comment by cojarbi** [comment]
Richard

Use the option I wrote before. Select all the stroke to path

AY
