### ISSUE TITLE
Traced vector returns previous trace

### ISSUE THREAD

**Issue by SigmazGFX** [openhardwarecoza/LaserWeb3#69]
I think I may have read of this before but I can't find the issue.

Loaded bitmap A and traced to vector.
Deleted bitmap A
Deleted traced A layer

Browser not refreshed

Loaded bitmap B
Trace to vector returned vector trace from bitmap A

**Comment by ghost** [comment]
Confirmed - reproducable with those steps...

**Comment by ghost** [comment]
Found why:  On removing the tab, i delete all the threejs objects, but I dont delete the origImage elements from the dom:  See fiverr.png (my first file) still present, with same ID

![elements](https://cloud.githubusercontent.com/assets/7695323/17381258/57937e48-59cb-11e6-9701-f5fd6a421162.PNG)

**Comment by ghost** [comment]
Done:  

Added ...

```
if (objectsInScene[layerIndex].type == "Mesh") {
       $("#origImage"+seq).remove();
 }
```
