### ISSUE TITLE
Raster generation is much slower than before.

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#74]
Using the same file, it used to take about 10 seconds, now it is taking 1 1/2 minutes.

**Comment by funinthefalls** [comment]
From the sys log:

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 99% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

: [Rasterizer] 100% done

Raster completed in 58311ms

: Raster Completed for butterfly-digital-stamp.png

: Preparing Gcode File: butterfly-digital-stamp.png

: Estimated Distance: 148.4 m

All sorts of duplicate % completed entries.

**Comment by ghost** [comment]
Remember,  we now change the resolution,  to match spot size.  Look at the
comments in laserraster.js with the math,  but basically we have a lot more
data to process when we really run 0.1mm lines.   Typically before if you
took a 72dpi image you had what?  A line every 25.4/72 = 0.3x mm?

**Comment by funinthefalls** [comment]
Ok,I understand, forgot about that.
