### ISSUE TITLE
image import top left

### ISSUE THREAD

**Issue by fumblz-n-action** [openhardwarecoza/LaserWeb3#76]
if you import an image into the top left corner it still imports the image to 0,0 when it comes to generating Gcode. the image is visually in the top left corner of the UI but  Y offsets aren't automatically compensated for. moving the y in negative offset results in gcode being generated outside the work environment and will result in machine crashes for people not using min and max endstops on both x,y

**Comment by funinthefalls** [comment]
This is more a "User has not configured his machine correctly" than a software issue. In fact LaserWeb is behaving exactly as it should (If you are like me it will only take Peter 7-8 attempts at explaining why it is correct before the light bulb over your head snaps on.

**Comment by ghost** [comment]
![topleft](https://cloud.githubusercontent.com/assets/7695323/17524055/398ccb02-5e5d-11e6-8549-03a576e7b4d5.PNG)

I tested just now and generates gcode at the top:  First draws a nice Y400 G0 move before starting the  path

Can you elaborate with screenshots?

**Comment by ghost** [comment]
Unless I misread your post, "negative offsets" - if you tell it to put the file outside the  envelope and home, prior to running, well of course you'll crash.  But think of the usecase of users without endstops (banggood lasers) - where you might use the SET ZERO - in which case you may consciously have negative offsets for some reason (so i also dont want to limit the x/yoffset inputs to positive numbers)

**Comment by fumblz-n-action** [comment]
it happens when you move the image with a -Y offset
![githublw1](https://cloud.githubusercontent.com/assets/19585624/17524457/52375ee4-5e24-11e6-825d-4672d218e53a.jpg)

**Comment by fumblz-n-action** [comment]
sorry i misworded it last night. i was getting pretty tired

**Comment by ghost** [comment]
Had a + instead of a Minus on https://github.com/openhardwarecoza/LaserWeb3/commit/b8103a1469cbba7abc7706acbb850b3eb69e6912#diff-c8ca0d5f58d3f66fb668f05549c2745bL191

**Comment by ghost** [comment]
I assume you would have commented if the fix (please test above) didnt work.  So closing this one (:
