### ISSUE TITLE
Read embedded bitmap dpi from  svg

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#78]
[Bitmap.svg.txt](https://github.com/openhardwarecoza/LaserWeb3/files/411896/Bitmap.svg.txt)
[png.svg.txt](https://github.com/openhardwarecoza/LaserWeb3/files/411902/png.svg.txt)

**Comment by ghost** [comment]
Basically done by @lautr3k 's latest commits - check if its inkscape or illustrator then reads dpi from settings page
