### ISSUE TITLE
Opening multiple times the same file name wont process

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#80]
I was testing the signal (PWM) sent to the laser with a V display and opened the same file multiple times to change the power setting in each and then generate a consecutive run. 

It stays as the image bellow. Only processes the first. 

So either same name file updates the current one or we process them all ( if possible ).

Tested with dxf and svg

<img width="1646" alt="screen shot 2016-08-10 at 6 44 49 pm" src="https://cloud.githubusercontent.com/assets/16444438/17574953/e855a5c8-5f2a-11e6-8b5d-6c0a57b1d141.png">

**Comment by cojarbi** [comment]
Further testing shows that the processing is not working if you just change the name of the file. You need to edit the file ( ai , inkscape ) and change the size itself for it to work but will stop at either 3 or 4

**Comment by cojarbi** [comment]
Attaching the files

[Archive.zip](https://github.com/openhardwarecoza/LaserWeb3/files/412368/Archive.zip)

**Comment by emteeoh** [comment]
Are you sure its not processing? I saw this a few weeks ago, but ultimately concluded it had generated g code for all the instances of the file, but mistakenly put all the g-code in the first image box... Not sure why I didn't file a bug...

**Comment by ghost** [comment]
I wouldnt stress this too much,  the new cam is coming along so quickly and
that portion is being rewritten anyway
