### ISSUE TITLE
Loading multiple files at the same time

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#81]
Could it be possible to load multiples files at the some time, including dropping the files?

**Comment by ghost** [comment]
Done in c5545802bf65700d8fb076287adfaf4283a84261.

**Comment by cojarbi** [comment]
Maybe this helps https://css-tricks.com/drag-and-drop-file-uploading/

**Comment by cojarbi** [comment]
@lautr3k Could you please also add drop file similar to Slacer?

**Comment by ghost** [comment]
@cojarbi Drag/Drop done dcd544b.
