### ISSUE TITLE
Continue processing raster on browser tab change

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#82]
Reference

http://stackoverflow.com/questions/15871942/how-do-browsers-pause-change-javascript-when-tab-or-window-is-not-active

**Comment by ghost** [comment]
Closing the issue.  Really nothing we can do:  Browser changes all setTimeouts to 1000ms (raster should be 10ms) = so it continues but 100x slower when not focussed.  Moral of the story, fire up another window instead of a tab?
