### ISSUE TITLE
Add default svg dpi resolution to config

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#84]
If as user mostly uses ai or inskcape they can set a default dpi and thus not need to change at every load 
<img width="326" alt="screen shot 2016-08-12 at 6 29 38 pm" src="https://cloud.githubusercontent.com/assets/16444438/17639742/efe669d0-60ba-11e6-9482-6320c965b89e.png">

**Comment by ghost** [comment]
Could work... but... Even better:  Remember the new work on SVGReader? 

We seem to be able to determine from the header meta data if its is Inkscape, Illustrator or something else (: -  Just waiting for Sebastien to finish the SVG Parser work - once thats merged,  I'll add in this automatic detection (:

: Note: See how the new parsers contains an "inkscape" object:
So, I can simply check for "if (svg.inkscape) { var dpi = 90; }" (;
![2016-08-10](https://cloud.githubusercontent.com/assets/7695323/17641853/f3f2ee60-6130-11e6-91a4-a100bf814190.png)

**Comment by cojarbi** [comment]
Oh man, how could i forget the black magic sebastien is cooking

**Comment by ghost** [comment]
Done !
![defaultsdpi](https://cloud.githubusercontent.com/assets/796149/17658248/a07e4a0e-62ca-11e6-8240-f5a03101cbe3.png)
