### ISSUE TITLE
viewer.js error message

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb3#89]
TypeError: Cannot read property 'userData' of null (http://localhost:8000/js/viewer.js on line 786)

Not surer what this error is?

**Comment by ghost** [comment]
Dont act like a user now... where, when what?  when does it error?

**Comment by ghost** [comment]
Probably by loading a mesh...

**Comment by funinthefalls** [comment]
Sorry, was going back over it so I could step by step it for you but you beat me to the punch.
Load bitmap.
Set DPI to 72
All other settings left untouched
Generate Gcode. 
Generates Gcode, but then spits out the error message in the trerminal. Not sure what it is a out, the Gcode looks fine.

**Comment by funinthefalls** [comment]
I checked with 4 different bitmaps, all 4 throw the same error after generating the gcode.

**Comment by funinthefalls** [comment]
Thanks, error is gone. That was some fast fixing guys!
