### ISSUE TITLE
Default location of the origin cone icon

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb3#92]
When starting LW the cone is located at 50,50

<img width="1697" alt="screen shot 2016-08-15 at 7 15 36 am" src="https://cloud.githubusercontent.com/assets/16444438/17664227/3bd1363c-62b8-11e6-8d0c-3897a7f6476f.png">

**Comment by ghost** [comment]
Fixed 7f08ae8

**Comment by ghost** [comment]
Hehe i actually purposely had it there,  i used it as a debug to see after
connecting to controller,   the first pos update put it on 0,0 (;    but no
biggie.  Leave it on 0,0   -  havent had a posstatus mishap in a while,
except the delayed last update (open issue)
