### ISSUE TITLE
Single File load DPI inconsistent

### ISSUE THREAD

**Issue by emteeoh** [openhardwarecoza/LaserWeb3#94]
I load an SVG created in Inkscape. It correctly loads, and is displayed at 90DPI, but the image pulldown in CAM shows it as being 25.4DPI. 
![screenshot from 2016-08-15 12 11 04](https://cloud.githubusercontent.com/assets/756072/17671059/ebb353b2-62e2-11e6-8842-58a3710d0019.png)

If I change the DPI to 90, the rendering remains unchanged, confirming it was loaded at 90DPI.
![screenshot from 2016-08-15 12 11 12](https://cloud.githubusercontent.com/assets/756072/17671068/fd760eb4-62e2-11e6-8893-859ea1dff377.png)

If I now change the DPI to 25.4, the rendering changes to what I expect 25.4 to look like. 
![screenshot from 2016-08-15 12 11 20](https://cloud.githubusercontent.com/assets/756072/17671101/32bc6884-62e3-11e6-9920-628a1233b1d2.png)

**Comment by ghost** [comment]
Relates to https://plus.google.com/+S%C3%A9bastienMischler-Skarab/posts/WcbDEKyS6gW  

Agreed though, the "default dpi" should be set to that file's input field... @lautr3k

**Comment by ghost** [comment]
I look at it tomorrow, need investigation... not so simple, if you reload the same file again it's work, or if you load multiple file too.

**Comment by emteeoh** [comment]
Just confirming:

If I load 1 file, DPI displays wrong.
If I load multiple files in a single operation, DPI is correct.
If I load multiple files, one at a time, DPI for the most recent file is wrong, but all the others are correct, even if they were incorrect before the latest file load.
If I load multiple files then one or more single files, the multiple files are correct, but the newest single file is incorrect.

**Comment by emteeoh** [comment]
I should point out that I set my default DPI to 90 (as well as for inkscape, 96 for adobe), so the 25.4 is coming from something hard-coded, not my config.
![screenshot from 2016-08-15 13 06 54](https://cloud.githubusercontent.com/assets/756072/17672198/2ae3a41e-62e9-11e6-90c5-8d10b8381a0b.png)

**Comment by ghost** [comment]
Thanks for the recap :)

**Comment by cojarbi** [comment]
I can confirm and replicate. 

Will add that if I delete the files via the tabs, the last preview stays on the screen even when the tab is gone. This is with svg

Mind that if one of the files has an embedded raster It will show the symptom above. 

Not sure if it's related, let me know and I open another case

AY

**Comment by emteeoh** [comment]
Ok, this is fixed, but the tool-path generation is not.  Should we leave this issue open, re-open 93, or make a new one? :)

**Comment by ghost** [comment]
This is the hard part of 'need to work on upcoming features,  and not break
existing features'  lol

**Comment by ghost** [comment]
We need a dev branch.

**Comment by ghost** [comment]
I know we do.  But look how much and how quickly we get feedback when break
live things (;   -  I count that a win (;

**Comment by ghost** [comment]
Reopened #93

**Comment by cojarbi** [comment]
Ohhh the feeling of being a lab mice, but this lab is amazing!!!  :) 

AY

**Comment by emteeoh** [comment]
If you had a dev branch, I'd probably be running it and giving you feedback anyhow. I'm trying these features _BECAUSE_ you said they're there, not because they're in main.
